# Generated by Django 4.2 on 2025-06-07 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="token",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Токен"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="user_role",
            field=models.CharField(
                choices=[(0, "Пользователь"), (1, "Администратор")],
                default="Пользователь",
                max_length=20,
                verbose_name="Роль пользвателя",
            ),
        ),
    ]
