# Generated by Django 4.2 on 2025-06-15 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_user_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="last_name",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Фамилия"
            ),
        ),
    ]
