# Generated by Django 4.2 on 2025-06-07 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_alter_advertisement_author_alter_review_author"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="ads",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="main.advertisement",
                verbose_name="Объявление",
            ),
        ),
    ]
